# Generated by Django 4.2.7 on 2025-05-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Họ và tên')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CMND/CCCD')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('join_date', models.DateField(verbose_name='Ngày vào làm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'Trung học phổ thông'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('master', 'Thạc sĩ'), ('phd', 'Tiến sĩ')], max_length=20, null=True, verbose_name='Trình độ học vấn')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bằng cấp')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chuyên ngành')),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Lương cơ bản')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Công ty')),
                ('position', models.CharField(max_length=100, verbose_name='Vị trí')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả công việc')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_histories', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Ngày hiệu lực')),
                ('old_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cũ')),
                ('new_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương mới')),
                ('reason', models.TextField(verbose_name='Lý do thay đổi')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_histories', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã vị trí')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vị trí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.position', verbose_name='Vị trí công việc'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('contract_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên hợp đồng')),
                ('contract_type', models.CharField(choices=[('probation', 'Thử việc'), ('definite', 'Xác định thời hạn'), ('indefinite', 'Không xác định thời hạn')], max_length=20, verbose_name='Loại hợp đồng')),
                ('work_form', models.CharField(blank=True, choices=[('fulltime', 'Toàn thời gian'), ('parttime', 'Bán thời gian'), ('remote', 'Từ xa'), ('hybrid', 'Kết hợp')], default='fulltime', max_length=20, null=True, verbose_name='Hình thức làm việc')),
                ('start_date', models.DateField(verbose_name='Ngày có hiệu lực')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='Ngày ký')),
                ('basic_salary', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('insurance_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương đóng bảo hiểm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiệu lực')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee', verbose_name='Nhân viên')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_contracts', to='employees.position', verbose_name='Vị trí công việc')),
            ],
            options={
                'verbose_name': 'Hợp đồng',
                'verbose_name_plural': 'Hợp đồng',
                'ordering': ['-start_date'],
            },
        ),
    ]
