# Generated by Django 4.2.7 on 2025-05-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryhistory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='SalaryHistory',
        ),
        migrations.DeleteModel(
            name='WorkHistory',
        ),
    ]
