# Generated by Django 4.2.7 on 2025-05-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryhistory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workhistory',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Nhân viên'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Vị trí công việc', 'verbose_name_plural': 'Vị trí công việc'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='code',
        ),
        migrations.RemoveField(
            model_name='position',
            name='is_active',
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'Trung học phổ thông'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('master', 'Thạc sĩ'), ('phd', 'Tiến sĩ'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Trình độ học vấn'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position', verbose_name='Vị trí'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='SalaryHistory',
        ),
        migrations.DeleteModel(
            name='WorkHistory',
        ),
    ]
