# Generated by Django 4.2.7 on 2025-05-13 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_remove_salaryhistory_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dependents',
            field=models.PositiveIntegerField(default=0, help_text='Số người phụ thuộc để tính giảm trừ gia cảnh', verbose_name='Số người phụ thuộc'),
        ),
        migrations.AddField(
            model_name='employee',
            name='discipline_amount',
            field=models.PositiveIntegerField(default=0, help_text='Số tiền phạt kỷ luật (VNĐ)', verbose_name='Tiền phạt kỷ luật'),
        ),
        migrations.AddField(
            model_name='employee',
            name='discipline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kỷ luật'),
        ),
        migrations.AddField(
            model_name='employee',
            name='discipline_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú kỷ luật'),
        ),
        migrations.AddField(
            model_name='employee',
            name='discipline_type',
            field=models.CharField(blank=True, choices=[('noi_quy', 'Vi phạm nội quy lao động'), ('quy_trinh', 'Không tuân thủ quy trình giảng dạy'), ('bao_mat', 'Vi phạm quy định bảo mật thông tin học viên')], max_length=20, null=True, verbose_name='Loại kỷ luật'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reward_amount',
            field=models.PositiveIntegerField(default=0, help_text='Số tiền thưởng (VNĐ)', verbose_name='Tiền thưởng'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reward_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày khen thưởng'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reward_note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú khen thưởng'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reward_type',
            field=models.CharField(blank=True, choices=[('thanh_tich', 'Thành tích công việc'), ('sang_kien', 'Sáng kiến cải tiến công việc'), ('tinh_than', 'Tinh thần làm việc và hỗ trợ đồng nghiệp')], max_length=20, null=True, verbose_name='Loại khen thưởng'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mã số thuế'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_exemption',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu nhân viên được miễn thuế TNCN', verbose_name='Được miễn thuế'),
        ),
        migrations.CreateModel(
            name='EmployeeReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('thanh_tich', 'Thành tích công việc'), ('sang_kien', 'Sáng kiến cải tiến công việc'), ('tinh_than', 'Tinh thần làm việc và hỗ trợ đồng nghiệp')], max_length=20, verbose_name='Loại khen thưởng')),
                ('amount', models.PositiveIntegerField(help_text='Số tiền thưởng (VNĐ)', verbose_name='Số tiền thưởng')),
                ('date', models.DateField(verbose_name='Ngày khen thưởng')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Khen thưởng nhân viên',
                'verbose_name_plural': 'Khen thưởng nhân viên',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_type', models.CharField(choices=[('noi_quy', 'Vi phạm nội quy lao động'), ('quy_trinh', 'Không tuân thủ quy trình giảng dạy'), ('bao_mat', 'Vi phạm quy định bảo mật thông tin học viên')], max_length=20, verbose_name='Loại kỷ luật')),
                ('amount', models.PositiveIntegerField(help_text='Số tiền phạt (VNĐ)', verbose_name='Số tiền phạt')),
                ('date', models.DateField(verbose_name='Ngày kỷ luật')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Kỷ luật nhân viên',
                'verbose_name_plural': 'Kỷ luật nhân viên',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('relationship', models.CharField(choices=[('con', 'Con'), ('vo_chong', 'Vợ/Chồng'), ('cha_me', 'Cha/Mẹ'), ('khac', 'Khác')], max_length=20, verbose_name='Quan hệ')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CMND/CCCD')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu giảm trừ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc giảm trừ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_persons', to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Người phụ thuộc',
                'verbose_name_plural': 'Người phụ thuộc',
                'ordering': ['employee', 'full_name'],
            },
        ),
    ]
