# Generated by Django 4.2.7 on 2025-05-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_employee_dependents_employee_discipline_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('discipline_type', models.CharField(choices=[('warning', 'Cảnh cáo'), ('fine', 'Phạt tiền'), ('suspension', 'Đình chỉ công tác'), ('other', 'Khác')], max_length=20, verbose_name='Loại kỷ luật')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disciplines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kỷ luật',
                'verbose_name_plural': 'Kỷ luật',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('reward_type', models.CharField(choices=[('bonus', 'Thưởng'), ('commission', 'Hoa hồng'), ('achievement', 'Thành tích'), ('other', 'Khác')], max_length=20, verbose_name='Loại khen thưởng')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khen thưởng',
                'verbose_name_plural': 'Khen thưởng',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='employeereward',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeereward',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='dependent',
            options={'ordering': ['-start_date'], 'verbose_name': 'Người phụ thuộc', 'verbose_name_plural': 'Người phụ thuộc'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Nhân viên'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Vị trí công việc', 'verbose_name_plural': 'Vị trí công việc'},
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='note',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='discipline_amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='discipline_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='discipline_note',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='discipline_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reward_amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reward_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reward_note',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reward_type',
        ),
        migrations.RemoveField(
            model_name='position',
            name='code',
        ),
        migrations.RemoveField(
            model_name='position',
            name='is_active',
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_persons', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(choices=[('child', 'Con'), ('spouse', 'Vợ/Chồng'), ('parent', 'Bố/Mẹ'), ('sibling', 'Anh/Chị/Em'), ('other', 'Khác')], max_length=20, verbose_name='Quan hệ'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dependents',
            field=models.PositiveIntegerField(default=0, verbose_name='Số người phụ thuộc'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'Trung học phổ thông'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('master', 'Thạc sĩ'), ('phd', 'Tiến sĩ'), ('other', 'Khác')], max_length=20, null=True, verbose_name='Trình độ học vấn'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.position', verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_exemption',
            field=models.BooleanField(default=False, verbose_name='Miễn thuế'),
        ),
        migrations.DeleteModel(
            name='EmployeeDiscipline',
        ),
        migrations.DeleteModel(
            name='EmployeeReward',
        ),
        migrations.AddField(
            model_name='reward',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='employees.employee'),
        ),
    ]
