# Generated by Django 4.2.7 on 2025-05-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bảng lương')),
                ('month', models.IntegerField(verbose_name='Tháng')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('processing', 'Đang xử lý'), ('approved', 'Đã duyệt'), ('paid', 'Đã thanh toán')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('attendance_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancesummary', verbose_name='Bảng chấm công tổng hợp')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí áp dụng')),
            ],
            options={
                'verbose_name': 'Bảng lương',
                'verbose_name_plural': 'Bảng lương',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('attendance_ratio', models.FloatField(default=0.0, verbose_name='Tỷ lệ hưởng lương')),
                ('standard_workdays',  models.IntegerField(default=0, verbose_name='Số công chuẩn')),
                ('actual_workdays', models.IntegerField(default=0, verbose_name='Số công thực tế')),
                ('unpaid_leave', models.FloatField(default=0.0, verbose_name='Số ngày nghỉ không lương')),
                ('gross_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng thu nhập')),
                ('deduction_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng khấu trừ')),
                ('net_salary', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thực lĩnh')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.payroll', verbose_name='Bảng lương')),
            ],
            options={
                'verbose_name': 'Chi tiết lương',
                'verbose_name_plural': 'Chi tiết lương',
                'unique_together': {('payroll', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khoản khấu trừ')),
                ('amount', models.FloatField(default=0.0, verbose_name='Giá trị')),
                ('is_percentage', models.BooleanField(default=True, verbose_name='Là phần trăm')),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền')),
                ('payroll_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payrolldetail', verbose_name='Chi tiết lương')),
            ],
            options={
                'verbose_name': 'Khoản khấu trừ',
                'verbose_name_plural': 'Khoản khấu trừ',
            },
        ),
        migrations.CreateModel(
            name='PayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phụ cấp')),
                ('amount', models.FloatField(default=0.0, verbose_name='Giá trị')),
                ('is_percentage', models.BooleanField(default=False, verbose_name='Là phần trăm')),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền')),
                ('payroll_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.payrolldetail', verbose_name='Chi tiết lương')),
            ],
            options={
                'verbose_name': 'Phụ cấp',
                'verbose_name_plural': 'Phụ cấp',
            },
        ),
    ]
