# Generated by Django 4.2.7 on 2025-05-13 12:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrolldeduction',
            options={'verbose_name': 'Khấu trừ lương', 'verbose_name_plural': 'Khấu trừ lương'},
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='attendance_summary',
        ),
        migrations.AddField(
            model_name='payroll',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã bảng lương'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='deduction_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dữ liệu khấu trừ'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.IntegerField(default=5, verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền/Tỷ lệ'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='is_percentage',
            field=models.BooleanField(default=True, verbose_name='Là tỷ lệ phần trăm'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên khấu trừ'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='payroll_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payrolldetail'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị khấu trừ'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='actual_workdays',
            field=models.FloatField(default=0.0, verbose_name='Số công thực tế'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='attendance_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, verbose_name='Tỷ lệ hưởng lương'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='standard_workdays',
            field=models.FloatField(default=0.0, verbose_name='Số công chuẩn'),
        ),
    ]
