# Generated by Django 4.2.7 on 2025-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payrolldeduction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrolldetail',
            options={'ordering': ['payroll', 'employee'], 'verbose_name': 'Chi tiết bảng lương', 'verbose_name_plural': 'Chi tiết bảng lương'},
        ),
        migrations.AlterUniqueTogether(
            name='payrolldetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='allowance_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng phụ cấp'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='discipline_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền phạt'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='income_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thuế TNCN'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='reward_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền thưởng'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='taxable_income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thu nhập tính thuế'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='actual_workdays',
            field=models.FloatField(verbose_name='Số công thực tế'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='attendance_ratio',
            field=models.FloatField(verbose_name='Tỷ lệ chuyên cần'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='basic_salary',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng khấu trừ'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='gross_salary',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Lương theo ngày công'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='net_salary',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thực lĩnh'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='standard_workdays',
            field=models.FloatField(verbose_name='Số công chuẩn'),
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='deduction_data',
        ),
    ]
