# Generated by Django 4.2.7 on 2025-05-13 17:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesummary_end_date_and_more'),
        ('employees', '0002_remove_salaryhistory_employee_and_more'),
        ('payroll', '0002_alter_payrolldeduction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrolldetail',
            options={'verbose_name': 'Chi tiết lương', 'verbose_name_plural': 'Chi tiết lương'},
        ),
        migrations.AddField(
            model_name='payroll',
            name='attendance_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='attendance.attendancesummary', verbose_name='Bảng chấm công'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='deduction_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dữ liệu khấu trừ'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='is_percentage',
            field=models.BooleanField(default=False, verbose_name='Là phần trăm'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='payroll_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payrolldetail', verbose_name='Chi tiết lương'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='actual_workdays',
            field=models.FloatField(default=0.0, verbose_name='Số công thực tế'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='attendance_ratio',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, verbose_name='Tỷ lệ hưởng lương'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='basic_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Lương cơ bản'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng khấu trừ'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='gross_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng thu nhập'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='net_salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Thực lĩnh'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='standard_workdays',
            field=models.FloatField(default=0.0, verbose_name='Số công chuẩn'),
        ),
        migrations.AlterUniqueTogether(
            name='payrolldetail',
            unique_together={('payroll', 'employee')},
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='allowance_amount',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='discipline_amount',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='reward_amount',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='taxable_income',
        ),
    ]
