# Generated by Django 4.2.7 on 2025-05-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_discipline_reward_remove_employeereward_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0003_alter_payrolldetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Bảng lương', 'verbose_name_plural': 'Bảng lương'},
        ),
        migrations.AlterModelOptions(
            name='payrolldeduction',
            options={'verbose_name': 'Khấu trừ', 'verbose_name_plural': 'Khấu trừ'},
        ),
        migrations.AlterModelOptions(
            name='payrolldetail',
            options={'ordering': ['employee__last_name', 'employee__first_name'], 'verbose_name': 'Chi tiết lương', 'verbose_name_plural': 'Chi tiết lương'},
        ),
        migrations.AddField(
            model_name='payroll',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrolldetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.PositiveIntegerField(null=True, verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên bảng lương'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='employees.position', verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('processing', 'Đang xử lý'), ('approved', 'Đã duyệt'), ('paid', 'Đã thanh toán'), ('disabled', 'Đã vô hiệu hóa')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='payrollallowance',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền/Tỷ lệ'),
        ),
        migrations.AlterField(
            model_name='payrollallowance',
            name='payroll_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='payroll.payrolldetail'),
        ),
        migrations.AlterField(
            model_name='payrollallowance',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền/Tỷ lệ'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='is_percentage',
            field=models.BooleanField(default=False, verbose_name='Là phần trăm'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá trị'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='actual_workdays',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Công thực tế'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='attendance_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tỷ lệ hưởng'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Khấu trừ khác'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='discipline_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền phạt kỷ luật'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_details', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='gross_salary',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng thu nhập'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='income_tax',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thuế TNCN'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_details', to='payroll.payroll'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='reward_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tiền khen thưởng'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='standard_workdays',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Công chuẩn'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='taxable_income',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thu nhập tính thuế'),
        ),
        migrations.AlterField(
            model_name='payrolldetail',
            name='unpaid_leave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Nghỉ không lương'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('month', 'year', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='payrolldetail',
            unique_together={('payroll', 'employee')},
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='code',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='allowance_amount',
        ),
    ]
