# Generated by Django 4.2.7 on 2025-05-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payrolldetail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolldetail',
            name='attendance_ratio',
        ),
    ]
