# Generated by Django 4.2.7 on 2025-05-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bảng chấm công')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('attendance_type', models.CharField(choices=[('shift', 'Theo ca'), ('daily', 'Theo ngày')], max_length=20, verbose_name='Hình thức chấm công')),
                ('apply_to_all_shifts', models.BooleanField(default=False, verbose_name='Chọn tất cả ca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí áp dụng')),
            ],
            options={
                'verbose_name': 'Bảng chấm công chi tiết',
                'verbose_name_plural': 'Các bảng chấm công chi tiết',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên ca làm việc')),
                ('code', models.CharField(max_length=20, verbose_name='Mã ca')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu ca')),
                ('check_in_start', models.TimeField(verbose_name='Chấm vào - Từ')),
                ('check_in_end', models.TimeField(verbose_name='Chấm vào - Đến')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc ca')),
                ('check_out_start', models.TimeField(verbose_name='Chấm ra - Từ')),
                ('check_out_end', models.TimeField(verbose_name='Chấm ra - Đến')),
                ('has_break', models.BooleanField(default=False, verbose_name='Có nghỉ giữa ca')),
                ('work_hours', models.FloatField(default=0, verbose_name='Giờ công')),
                ('work_days', models.FloatField(default=1, verbose_name='Ngày công')),
                ('normal_day_coefficient', models.FloatField(default=1, verbose_name='Hệ số ngày thường')),
                ('rest_day_coefficient', models.FloatField(default=2, verbose_name='Hệ số ngày nghỉ')),
                ('holiday_coefficient', models.FloatField(default=3, verbose_name='Hệ số ngày lễ')),
                ('deduct_if_no_check_in', models.BooleanField(default=False, verbose_name='Trừ công nếu không có giờ vào')),
                ('deduct_if_no_check_out', models.BooleanField(default=False, verbose_name='Trừ công nếu không có giờ ra')),
                ('apply_to_all', models.BooleanField(default=False, verbose_name='Toàn đơn vị')),
                ('employees', models.ManyToManyField(blank=True, to='employees.employee', verbose_name='Danh sách nhân viên')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Các ca làm việc',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên bảng chấm công tổng hợp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_records', models.ManyToManyField(to='attendance.attendancerecord', verbose_name='Danh sách bảng chấm công chi tiết')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position', verbose_name='Vị trí áp dụng')),
            ],
            options={
                'verbose_name': 'Bảng chấm công tổng hợp',
                'verbose_name_plural': 'Các bảng chấm công tổng hợp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='work_shifts',
            field=models.ManyToManyField(blank=True, to='attendance.workshift', verbose_name='Ca làm việc'),
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày chấm công')),
                ('paid_work_days', models.FloatField(default=1, verbose_name='Số công hưởng lương')),
                ('actual_work_days', models.FloatField(default=1, verbose_name='Số công đi làm thực tế')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('attendance_status', models.CharField(choices=[('not_absent', 'Không nghỉ'), ('permitted_absence', 'Nghỉ có phép'), ('unpermitted_absence', 'Nghỉ không phép'), ('regime_absence', 'Nghỉ theo chế độ')], default='not_absent', max_length=20, verbose_name='Nghỉ')),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='attendance.attendancerecord', verbose_name='Bảng chấm công')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên')),
                ('work_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift', verbose_name='Ca làm việc')),
            ],
            options={
                'verbose_name': 'Chấm công hàng ngày',
                'verbose_name_plural': 'Chấm công hàng ngày',
                'unique_together': {('attendance_record', 'employee', 'date')},
            },
        ),
    ]
