# Generated by Django 4.2.7 on 2025-05-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_salaryhistory_employee_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='standard_workdays',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5, verbose_name='Số công chuẩn'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='transferred',
            field=models.BooleanField(default=False, verbose_name='Đã chuyển tính lương'),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdays', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Số công làm việc')),
                ('paid_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghỉ có lương')),
                ('unpaid_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghỉ không lương')),
                ('policy_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nghỉ chế độ')),
                ('late_early_minutes', models.IntegerField(default=0, verbose_name='Đi muộn/về sớm (phút)')),
                ('attendance_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='attendance.attendancesummary', verbose_name='Bảng chấm công tổng hợp')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Chấm công nhân viên',
                'verbose_name_plural': 'Chấm công nhân viên',
                'unique_together': {('employee', 'attendance_summary')},
            },
        ),
    ]
