# Generated by Django 4.2.7 on 2025-05-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_discipline_reward_remove_employeereward_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_attendancesummary_end_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='attendance_summary',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='employees',
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['employee__last_name', 'employee__first_name'], 'verbose_name': 'Bảng chấm công chi tiết', 'verbose_name_plural': 'Bảng chấm công chi tiết'},
        ),
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Bảng chấm công tổng hợp', 'verbose_name_plural': 'Bảng chấm công tổng hợp'},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attendance_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesummary'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late_early_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Đi muộn/về sớm (phút)'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='normal_work_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Công ngày thường'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='rest_work_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Công ngày nghỉ'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='standard_work_days',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Công chuẩn'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='unpaid_leave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Nghỉ không lương'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='month',
            field=models.PositiveIntegerField(null=True, verbose_name='Tháng'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên bảng chấm công'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_summaries', to='employees.position', verbose_name='Vị trí'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('attendance_summary', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('month', 'year', 'position')},
        ),
        migrations.DeleteModel(
            name='DailyAttendance',
        ),
        migrations.DeleteModel(
            name='EmployeeAttendance',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='apply_to_all_shifts',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attendance_type',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='work_shifts',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='attendance_records',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='standard_workdays',
        ),
        migrations.RemoveField(
            model_name='attendancesummary',
            name='start_date',
        ),
        migrations.DeleteModel(
            name='WorkShift',
        ),
    ]
