# Generated by Django 4.2.7 on 2025-05-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesummary_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='month',
            field=models.IntegerField(default=1, verbose_name='Tháng'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Năm'),
        ),
    ]
